workspace/.c9/metadata/workspace/python1/urls.py
{"filter":false,"title":"urls.py","tooltip":"/python1/urls.py","undoManager":{"mark":10,"position":10,"stack":[[{"start":{"row":10,"column":11},"end":{"row":10,"column":12},"action":"insert","lines":["s"],"id":18}],[{"start":{"row":10,"column":12},"end":{"row":10,"column":13},"action":"insert","lines":["c"],"id":19}],[{"start":{"row":10,"column":13},"end":{"row":10,"column":14},"action":"insert","lines":["r"],"id":20}],[{"start":{"row":10,"column":14},"end":{"row":10,"column":15},"action":"insert","lines":["u"],"id":21}],[{"start":{"row":10,"column":15},"end":{"row":10,"column":16},"action":"insert","lines":["m"],"id":22}],[{"start":{"row":10,"column":15},"end":{"row":10,"column":16},"action":"remove","lines":["m"],"id":23}],[{"start":{"row":10,"column":14},"end":{"row":10,"column":15},"action":"remove","lines":["u"],"id":24}],[{"start":{"row":10,"column":13},"end":{"row":10,"column":14},"action":"remove","lines":["r"],"id":25}],[{"start":{"row":10,"column":12},"end":{"row":10,"column":13},"action":"remove","lines":["c"],"id":26}],[{"start":{"row":10,"column":11},"end":{"row":10,"column":12},"action":"remove","lines":["s"],"id":27}],[{"start":{"row":9,"column":0},"end":{"row":10,"column":0},"action":"remove","lines":["    url(r'^contacts/', include('contacts.urls', namespace=\"contacts\")),",""],"id":28}]]},"ace":{"folds":[],"scrolltop":0,"scrollleft":0,"selection":{"start":{"row":9,"column":0},"end":{"row":9,"column":0},"isBackwards":false},"options":{"guessTabSize":true,"useWrapMode":false,"wrapToView":true},"firstLineState":{"row":72,"mode":"ace/mode/python"}},"timestamp":1441922744501,"hash":"0fff7643df3a3c780a35e571cccd28a0b46d460f"}

workspace/python1/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'python1.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('scrum.urls', namespace="scrum")),

)

workspace/scrum/urls.py
from django.conf.urls import patterns, url

from scrum import views

urlpatterns = patterns('',
    # ex: /scrum/
    url(r'^$', views.index, name='index'),
    # ex: /scrum/2/
    url(r'^(?P<task_id>\d+)/$', views.detail, name='detail'),
    # ex: /scrum/5/results/
    url(r'^(?P<task_id>\d+)/assign/$', views.assign, name='assign'),
    # ex: /scrum/5/active/
    url(r'^(?P<task_id>\d+)/status/$', views.status, name='status'),

)

workspace/scrum/models.py
from django.conf import settings
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse


# Create your models here.
class Task(models.Model):
    

    STATUS_TODO = 1
    STATUS_IN_PROGRESS = 2
    STATUS_TESTING = 3
    STATUS_DONE = 4

    STATUS_CHOICES = (
        (STATUS_TODO, _('Not Started')),
        (STATUS_IN_PROGRESS, _('In Progress')),
        (STATUS_TESTING, _('Testing')),
        (STATUS_DONE, _('Done')),
    )

    name = models.CharField(max_length=100)
    description = models.TextField(blank=True, default='')
    status = models.SmallIntegerField(choices=STATUS_CHOICES,
                                      default=STATUS_TODO)
    order = models.SmallIntegerField(default=0)
    assigned = models.ForeignKey(settings.AUTH_USER_MODEL,
                                 null=True, blank=True)
    started = models.DateField(blank=True, null=True)
    due = models.DateField(blank=True, null=True)
    completed = models.DateField(blank=True, null=True)

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ('order',)
        
    def __unicode__(self):
        return self.name

workspace/scrum/views.py
from django.conf import settings
from django.contrib.auth import get_user_model as user_model
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext, loader
from scrum.models import Task

User = user_model()

# Create your views here.
def index(request):
    #title = "Hello, world. You're at the Contacts index.. \r\n\n"
    backlog_tasks = Task.objects.filter(assigned = None)
    assigned_tasks = Task.objects.exclude(assigned = request.user)
    my_tasks = Task.objects.filter(assigned = request.user)

    template = loader.get_template('scrum/index.html')
    context = RequestContext(request, {
        'backlog_tasks_list': backlog_tasks,
        'assigned_tasks_list': assigned_tasks,
        'tasks_list': my_tasks,
    })
    return HttpResponse(template.render(context))
    
def detail(request, task_id):
    task = get_object_or_404(Task, pk=task_id)
    return render(request, 'scrum/detail.html', {
        'task': task,
        'current_user': User,
        'status_list':Task.STATUS_CHOICES,
        })

def assign(request, task_id):
    Task.objects.filter(pk=task_id).update(assigned=request.user)
    return HttpResponseRedirect('/')
    
def status(request, task_id):
    Task.objects.filter(pk=task_id).update(status=request.POST["status_id"] )
    return HttpResponseRedirect('/')

workspace/scrum/templates/scrum/detail.html
<h1>{{ task.name }}  </h1>
<p>{{ task.description }}</p>

<br/>
{% if task.assigned  %}

{% if user.username == task.assigned.username %}
<p><Strong> Would you to change the status of the task? </strong>
<form action="{% url 'scrum:status' task.id  %}" method="post">
    {% csrf_token %}

    <select name="status_id">
    {% for id, desc in status_list %}
        {% if id == task.status %}
            <option value="{{id}}" selected="selected">{{desc}}</option>
        {% else %}
            <option value="{{id}}">{{desc}}</option>
        {% endif %}
    {% endfor %}
</select>
    <input type="submit" value="Ok" />

</form>
</p>
{% else %}

    <p><Strong> You are viewing task that is already assigned to another user  </strong></p>
{% endif %}

{% else %} 
<p><Strong> Task is not yet assigned ! Would you like this to be assigned to you? </strong>
<form action="{% url 'scrum:assign' task.id %}" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes! Assign Me!" />

</form>
 </p>
{% endif %}

<a href="{% url 'scrum:index'%}">View Tasks </a>

workspace/scrum/templates/scrum/index.html
<div style='margin:0,40px'>

<div>
    <div> My Tasks</div>
    <div style="{{  'background-color:lightgreen'}}">
    <table>
        
    {% if tasks_list %}
    <tr><td width="400px">Task Name</td><td width="100px">Assigned to</td><td width="100px">Status</td></tr>
    {% for task in tasks_list %}
    <tr>
            <td><a href="{% url 'scrum:detail' task.id %}">{{ task.name }} </a></td>
            <td>{{task.assigned}}</td>
            <td>{{task.status}}</td>

    </tr>
    {% endfor %}
    {% else %}
        <tr>
            <td>No task to display</td>

        </tr>

    {% endif %}

    </table>

    </div>
</div>
<br/>
<br/>

<div>
    <div> Sprint Tasks</div>
    <div style="{{  'background-color:lightgrey'}}">
    <table>
        

    {% if assigned_tasks_list %}
    <tr><td width="400px">Task Name</td><td width="100px">Assigned to</td><td width="100px">Status</td></tr>
    {% for task in assigned_tasks_list %}
    <tr>
            <td><a href="{% url 'scrum:detail' task.id %}">{{ task.name }} </a></td>
            <td>{% if task.assigned %}{{task.assigned.username}} {% else %} not assigned {% endif %}</td>
            <td>{{task.status}}</td>

    </tr>
    {% endfor %}
    {% else %}
    <tr>
            <td>No task to display</td>

    </tr>
    {% endif %}


    
    </table> 

    </div>
</div>
</div>